CREATE DATABASE `dbtuts` ;
CREATE TABLE `dbtuts`.`users` (
`user_id` INT( 10 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`name` VARCHAR( 50 ) NOT NULL ,
`nName` VARCHAR( 25 ) NOT NULL ,
`email` VARCHAR(50) NOT NULL,
`hAd` VARCHAR( 100 ),
`gender` VARCHAR(20) NOT NULL,
`cNum` VARCHAR(14) NOT NULL,
`message` VARCHAR(255)
) ENGINE = InnoDB;